mode: blankevoort_mcl

data:
  x_noise: 0
  y_noise: 20 
  n_points: 200
  x_min: 0.20 # milimeter domain
  x_max: 0.30 

# Use these for ground truth
trilinear_mcl:
    stiffness_1: 30 # N per mm
    stiffness_2: 60  # MPa
    stiffness_3: 120 # Make large
    length_0: 0.2 # meters
    a_1: 1.06 # times length_0
    a_2: 1.15 # times length_0

blankevoort_mcl:
    linear_elastic: 60 # N per mm
    alpha: 0.06 # Transition length, at 6% strain
    l_0: 0.2 # meters
    f_ref: 0.02 # strain




prior_distribution_lcl_tri:
  # k_1, k_2, k_3, x_1, x_2
  
  # k_2 ranges from about 100-600, so mean 350, std 250
  # k_1 is usually half k_2
  # k_3 is generally unexplored, so we make it large

  # x_1 is set to 0.06 in most experiments (they report it was half, which is 0.03)
  # We will give this a relatively tight prior

  # x_2 is about 4-15 mm from my test, we need to convert to strain,
  # Assume length is about 48.15 mm
  # This means we have about 0.01 to 0.3 strain
  # 0.01 doesn't make much sense, since it definately needs to be larger than 0.06
  # So les put mean at 0.15, std at 0.15, is has large variance but thats ok!

  # We multiply k's by 8.76 (cross section) to get Newtons per strain

  # For now assume all values are independent
  mean: [1533.0, 3066.0, 10000, 0.19, 1.06, 1.15]
  std: [1095.0, 2190.0, 10000, 0.02, 0.02, 0.02]

prior_distribution_lcl_blankevoort:
    mean: [0.06, 3066.0]
    std: [0.02, 2190.0]