input_data:
    femur_length: 500 # All lengths in mm
    femur_perp: 100
    tibia_perp: 100
    tibia_para: 50
    application_length: 200
    theta: 0.1 #radians, theta_sym

    # Defines the ground truth parameters in the mechanical model
    ligament_slack_length: 45 # 30 mm
    ligament_transition_point: 0.06 # measured in strain %, always greater than 1
    ligament_stiffness: 60 # Newtons per mm

    app_Fx: app_Fx_sym