input_data:
    femur_length: 0.5
    femur_perp: 0.1
    tibia_perp: 0.1
    tibia_para: 0.05
    application_length: 0.20
    theta: 0.1 #radians, theta_sym

    ligament_slack_length: 0.03
    ligament_transition_point: 0.02
    ligament_stiffness: 2 # Newtons per meter

    app_Fx: app_Fx_sym